### ISSUE TITLE
推理的面部分辨率, 推理生成时间. Facial resolution of inference, inference generation time

### ISSUE THREAD

**Issue by johnny761127** [anliyuan/Ultralight-Digital-Human#42]
请教下,
Please help to tell me, 

1. 推理时的面部分辨率, 目前最高支持多少？
Facial resolution during inference, what is the maximum currently supported?

2. 如果之后的流式推理, 生成第一幀数字人说话形象的秒数为何(STA, Speech to Animation)？
If streaming inference is performed later, how much time does it take to generate the first frame of digital human speaking image(STA, Speech to Animation) ?

3. 如果非流式推理, 输入音频秒数与数字人说话形象生成秒数, 是1:x ？
If there is non-streaming inference, the number of seconds of input audio and the number of seconds of digital human speaking image generation are 1:x ?

谢谢您的贡献
Thank you for your contribution

**Comment by anliyuan** [comment]
1、你可以自己设置。
2、wenet300多ms hubert1s
3、需要看你的设备是什么设备。

**Comment by johnny761127** [comment]
1. 针对推理生成的面部包含嘴型, 推理生成的最高分辨率, 可以设置512*512以上吗（如Wav2lip算法, 最高支持512*512), 还是多少分辨率, 因为我看您demo的视频, 嘴型部分的分辨率没有很高的样子
2. 流式推理, 以wenet300多ms来说, 是从第1幀开始, 花300多ms推理生成嘴型, 然后每幀不间断连续生成吗, 中间不需要任何等待时间？
还是第1幀花300多ms推理生成嘴型, 第2幀需要”等待“第1幀300多ms推理生成完成后, 才再花300多ms推理生成嘴型
3
a. 输入音频秒数与数字人说话形象生成秒数, 您使用哪款NVIDIA GPU做推理, 大约是1：X?                                                            
b. 以及您用的手持装置, 是什么样的CPU或GPU来推理, 大约是1：Y?
谢谢

**Comment by anliyuan** [comment]
1、你可以自己在datasetsss.py里面设置
2、每凑够一帧就推理一次。
2080ti 100～200fps
iphonexr上25～30 fps

**Comment by johnny761127** [comment]
2. 以wenet300多ms来说,  那每幀推理还是要花300多ms, 对吧
3. iPhoneXR, 您是如何将CUDA框架部署在手机上的, 或是不用CUDA框架而是用其他方式来部署
谢谢

**Comment by anliyuan** [comment]
2、每次推理需要攒够一定量的音频，推理并不需要花很多时间。
3、iphone上没有nvidia cuda，但可以使用coreml

**Comment by johnny761127** [comment]
谢谢您的说明

**Comment by johnny761127** [comment]
谢谢您的说明
