### ISSUE TITLE
谁下载的有encoder.onnx，麻烦放一下百度网盘，谷歌的下不动

### ISSUE THREAD

**Issue by einsqing** [anliyuan/Ultralight-Digital-Human#49]
Download wenet encoder.onnx from https://drive.google.com/file/d/1e4Z9zS053JEWl6Mj3W9Lbc9GDtzHIg6b/view?usp=drive_link

**Comment by huipengo** [comment]
通过网盘分享的文件：encoder.onnx
链接: https://pan.baidu.com/s/1_DgwqCuhKUog8lk4puz1Lg?pwd=8888 提取码: 8888

兄弟，不用谢！
