### ISSUE TITLE
嘴巴角度稍微大一点，人脸检测嘴可能超出这个框了，最后生成的就很抖，有什么办法解决么？

### ISSUE THREAD

**Issue by einsqing** [anliyuan/Ultralight-Digital-Human#75]
![image](https://github.com/user-attachments/assets/55d6f9ea-4e16-4342-bc7f-f690f720e755)
@anliyuan

**Comment by anliyuan** [comment]
拉最新代码试试

**Comment by einsqing** [comment]
是最新的代码，刚训练的
