### ISSUE TITLE
移动端实时性

### ISSUE THREAD

**Issue by consistent1997** [anliyuan/Ultralight-Digital-Human#77]
大佬您好，我想请教一下，使用wenet以及更小的通道数，部署到移动端，整个推理步骤包括数据的前后处理等加起来，可以达到实时吗？或者说移动端实时具体对模型和参数设置有没有什么细节要求？希望大佬解答一下，谢谢！

**Comment by anliyuan** [comment]
移动端上实时没问题

**Comment by consistent1997** [comment]
好的，谢谢大佬！另外方便说一下移动端使用的设备么？

**Comment by anliyuan** [comment]
> 好的，谢谢大佬！另外方便说一下移动端使用的设备么？

我是在iphonexr上测的

**Comment by consistent1997** [comment]
好的，感谢，那我先关闭问题了
