### ISSUE TITLE
这是单人模型么？能训练泛化么？

### ISSUE THREAD

**Issue by einsqing** [anliyuan/Ultralight-Digital-Human#8]

**Comment by anliyuan** [comment]
我没试过，不能保证。你可以搞一批数据试一试

**Comment by einsqing** [comment]
用的hubert，训练出来的嘴巴有点抖，有啥办法解决么？

**Comment by anliyuan** [comment]
> 用的hubert，训练出来的嘴巴有点抖，有啥办法解决么？

可以把视频传上来看一下

**Comment by einsqing** [comment]
https://github.com/user-attachments/assets/bfa15cec-07b1-447b-adbf-57f1cdb32957

**Comment by anliyuan** [comment]
> 1.mp4 
> 前面还好，后面说话看起来对不上了

训练了多少个epoch？
可以把你的训练视频私发给我，我试一下

**Comment by einsqing** [comment]
有v么？默认的200epoch

**Comment by anliyuan** [comment]
> 有v么？默认的200epoch
tngt1206@163.com

**Comment by einsqing** [comment]
ok，发过了

**Comment by einsqing** [comment]
> 我没试过，不能保证。你可以搞一批数据试一试

我测试了同时训练多个人，用出来的多个模型推理，一会儿这个人效果好，一会儿这个人效果差
