### ISSUE TITLE
我的嘴巴没怎么变，是数据集的原因？还是？

### ISSUE THREAD

**Issue by gg22mm** [anliyuan/Ultralight-Digital-Human#99]
生成：
https://github.com/user-attachments/assets/3b9451d9-9758-4ee2-a858-678319cb2764

原文件：
https://pan.baidu.com/s/1OvxfQJqRPW3TsfKVNIJ8IQ?pwd=u333

**Comment by HelloLittleJoey** [comment]
我的也没变，demo还不是太成熟吧

**Comment by qwert1887** [comment]
@gg22mm 看来你的原始视频，背景音乐去除了么？

**Comment by gg22mm** [comment]
我试了用 康辉老师的口播 就不会，看来真可能是视频的原因

**Comment by lordlxh** [comment]
推理的语音是16kHz的吗？
